FROM python:3.11-slim-bookworm

RUN groupadd -g 1000 mesh && useradd -ml -u 1000 -g 1000 -s /bin/bash mesh

RUN pip install --upgrade pip -qq

USER mesh

VOLUME /home/mesh

COPY ./meshtastic-matrix-relay /home/mesh/app
COPY ./config.yaml /home/mesh/app/config.yaml

RUN pip install -qq -r /home/mesh/app/requirements.txt

RUN cp -r /home/mesh /mnt

WORKDIR /home/mesh
