FROM python:3.11-slim-bookworm

RUN groupadd -g 1000 mesh && useradd -ml -u 1000 -g 1000 -s /bin/bash mesh

RUN pip install --upgrade pip -qq

USER mesh

COPY meshtastic-matrix-relay/requirements.txt /tmp/requirements.txt

RUN pip install -qq -r /tmp/requirements.txt

WORKDIR /home/mesh

RUN echo "export PATH=$HOME/.local/bin:$PATH" >> .bashrc

CMD ["python app/main.py"]
