FROM python:3.11-slim-bookworm

RUN groupadd -g 1000 mesh && useradd -ml -u 1000 -g 1000 -s /bin/bash mesh

RUN pip install --upgrade pip -qq

USER mesh

COPY meshtastic-matrix-relay/requirements.txt /home/mesh/requirements.txt

RUN pip install -qq -r /home/mesh/requirements.txt

USER root

RUN  mv /home/mesh/.local/bin/* /usr/local/bin/

USER mesh

WORKDIR /home/mesh

CMD ["bash"]
